### PR TITLE
Updated podspec to have FLEX 3 as dependency

### PR DESCRIPTION
**Pull request by ajpallares**
Updated the SDOSFLEX .podspec to have version 3 of FLEX as dependency.

### CODE REVIEW

**Comment by RafaelFernandezAlv** [comment]
Thanks for you contribution! I will review in the next days

**Comment by RafaelFernandezAlv** [comment]
Hello,

I reviewed the pull request and I discovered two issues for make the merge:
- You need update the file Changelog.md
- You need make a pod install of the sample project.

Please, solve the issues for make the merge. Thanks!

**Comment by ajpallares** [comment]
You are totally right @RafaelFernandezAlv. I'm going to solve these two issues as soon as possible.

**Comment by ajpallares** [comment]
After I did the `pod install`, no changes were detected. And then I saw that the podfile.lock is added to the gitignore.

On the other hand, I could add a line to the Changelog.md of the type:
> Updated podspec to have FLEX 3 as dependency.

But I am not sure if this should be done later when a new release is being pushed. For starters, I do not know whether this only change will make a new release or more changes will be added to the next release. So, I cannot know the next version of this library either.

How should we proceed?

**Comment by RafaelFernandezAlv** [comment]
Add to the Changelog.md that line and the first line must be reference to the [HEAD] development. In the next release I will change HEAD to the version of library

If you can remove podfile.lock of .gitignore

**Comment by ajpallares** [comment]
Done.

The line I added to the Changelog was in English (I found it appropriate this way). Tell me if you believe Spanish should be used instead.

**Comment by RafaelFernandezAlv** [comment]
The new version of library with this changes is now available

Thanks @ajpallares!

**Pull request merged**
